command:
  - streamlit
  - run
  - app.py
env:
  - name: GENIE_SPACE_ID
    value: "01f133e63d4d141cad9ba61f50ccebf7"
  - name: LAKEBASE_INSTANCE_NAME
    value: "primeins-lakebase"
  - name: LAKEBASE_HOST
    value: "ep-late-tooth-d8dc2eg6.database.us-east-2.cloud.databricks.com"
  - name: LAKEBASE_DATABASE
    value: "primeins"
resources:
  - name: lakebase_db
    description: "PrimeInsurance Lakebase serving layer"
    database:
      instance_name: primeins-lakebase
      database_name: primeins
      permission: CAN_CONNECT_AND_CREATE
